CREATE TABLE `player` (
  `player_id` INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '玩家id',
  `player_name` VARCHAR(32) DEFAULT NULL COMMENT '玩家名',
  `passward` VARCHAR(32) DEFAULT NULL COMMENT '密码',
  `level` INT(11) DEFAULT NULL COMMENT '等级',
  `exp` INT(11) DEFAULT NULL COMMENT '经验'
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin